accepted = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "CC0-1.0",
    "BSL-1.0",
    "BUSL-1.1",
    "Unicode-3.0",
    "Unlicense",
    "MPL-2.0",
    "OpenSSL",
    "CDLA-Permissive-2.0",
]
