[package]
name        = "vmm-cli"
version.workspace   = true
edition.workspace   = true
authors.workspace   = true
license.workspace   = true
repository.workspace = true

[[bin]]
name = "vmm"
path = "src/main.rs"

[dependencies]
vmm-grpc.workspace  = true
tonic.workspace     = true
tokio.workspace     = true
anyhow.workspace    = true
clap.workspace      = true
tracing.workspace   = true
tracing-subscriber.workspace = true
serde_json.workspace = true
tower.workspace      = true
hyper-util.workspace = true
